/**
 * Certification dataset scale presets (Computer Shop Phase 1).
 * Counts are intentional business activity — not random noise.
 */

export var CERT_DATASET_SIZES = {
  small: {
    id: "small",
    label: "Small",
    months: 2,
    stockProducts: 36,
    customers: 18,
    suppliers: 8,
    others: 6,
    purchases: 18,
    sales: 42,
    salesReturns: 8,
    purchaseReturns: 5,
    quotations: 12,
    quotationConversions: 4,
    expenses: 14,
    repairs: 12,
    extra3pRepairs: 3,
    damageEntries: 4,
    assets: 4,
    manualReceivables: 6,
    manualPayables: 5,
    voidedSales: 2,
    voidedPurchases: 1,
    editedSales: 2,
    editedPurchases: 2,
  },
  medium: {
    id: "medium",
    label: "Medium",
    months: 3,
    stockProducts: 72,
    customers: 36,
    suppliers: 14,
    others: 10,
    purchases: 36,
    sales: 90,
    salesReturns: 16,
    purchaseReturns: 10,
    quotations: 28,
    quotationConversions: 8,
    expenses: 28,
    repairs: 24,
    extra3pRepairs: 6,
    damageEntries: 8,
    assets: 6,
    manualReceivables: 12,
    manualPayables: 10,
    voidedSales: 3,
    voidedPurchases: 2,
    editedSales: 4,
    editedPurchases: 3,
  },
  large: {
    id: "large",
    label: "Large",
    months: 4,
    stockProducts: 120,
    customers: 64,
    suppliers: 22,
    others: 16,
    purchases: 58,
    sales: 150,
    salesReturns: 28,
    purchaseReturns: 16,
    quotations: 48,
    quotationConversions: 12,
    expenses: 42,
    repairs: 40,
    extra3pRepairs: 10,
    damageEntries: 12,
    assets: 8,
    manualReceivables: 20,
    manualPayables: 16,
    voidedSales: 5,
    voidedPurchases: 3,
    editedSales: 6,
    editedPurchases: 5,
  },
};

export function resolveCertScale(sizeId) {
  var key = String(sizeId || "medium").toLowerCase();
  return CERT_DATASET_SIZES[key] || CERT_DATASET_SIZES.medium;
}
