/**
 * TechonERP Master Edition — category groups, sub-categories, units, and workflows.
 * workflow: "standard" | "glass_cut"
 */

export var MASTER_EDITION_ID = "master";

export var CATEGORY_GROUPS = [
  {
    id: "phones_tablets",
    label: "Phones | Tablets & Parts",
    emoji: "📱",
    workflow: "standard",
    units: ["Pcs", "Box", "Set", "Pair", "Roll", "Kit"],
    subCategories: [
      "Mobile Phones",
      "Phone Accessories",
      "Phone Repair Parts",
      "iPads & Tablets",
      "Tablet Accessories",
      "Other",
    ],
    legacyIndustries: ["tech"],
  },
  {
    id: "computers",
    label: "Computers & Parts",
    emoji: "💻",
    workflow: "standard",
    units: ["Pcs", "Box", "Set", "Pair", "Roll", "Kit"],
    subCategories: [
      "Desktops",
      "Laptops",
      "All-in-One PCs",
      "Printers & Scanners",
      "Computer Accessories",
      "Computer Repair Parts",
      "Networking & WiFi",
      "UPS & Power Backup",
      "Software & Licenses",
      "Other",
    ],
    legacyIndustries: ["tech"],
  },
  {
    id: "cctv_security",
    label: "CCTV & Security",
    emoji: "📹",
    workflow: "standard",
    units: ["Pcs", "Box", "Set", "Pair", "Roll", "Kit", "Metre"],
    subCategories: [
      "CCTV Cameras",
      "DVR & NVR",
      "Security Systems",
      "Cables & Connectors",
      "Accessories",
      "Other",
    ],
    legacyIndustries: ["tech"],
  },
  {
    id: "electronics",
    label: "Electronics & AV",
    emoji: "📺",
    workflow: "standard",
    units: ["Pcs", "Box", "Set", "Pair", "Roll", "Kit"],
    subCategories: [
      "TV & Home Electronics",
      "Gaming & Consoles",
      "Cameras & Photography",
      "Audio & Speakers",
      "Accessories",
      "Other",
    ],
    legacyIndustries: ["tech"],
  },
  {
    id: "glass_glazing",
    label: "Glass & Glazing",
    emoji: "🪟",
    workflow: "glass_cut",
    units: ["Sheet", "Sq Ft", "Sq M", "Pcs", "Metre", "Panel", "Set", "Pair", "Box", "Job"],
    subCategories: [
      "Plain Float Glass",
      "Tempered Glass",
      "Laminated Glass",
      "Mirrors",
      "Frosted & Decorative Glass",
      "Tinted & Reflective Glass",
      "Insulated Glass (DGU)",
      "Safety & Wire Glass",
      "Shower Enclosures & Partitions",
      "Aluminium & uPVC Frames",
      "Glass Fittings & Hardware",
      "Sealants & Silicones",
      "Custom Cut Glass",
      "Glass Blocks & Specialty",
      "Other",
    ],
    legacyIndustries: ["glass"],
  },
  {
    id: "electrical",
    label: "Electrical & Wiring",
    emoji: "⚡",
    workflow: "standard",
    units: ["Pcs", "Metre", "Roll", "Box", "Set", "Pair", "Bundle", "Kit"],
    subCategories: [
      "Electrical Wiring & Cables",
      "Switches & Sockets",
      "Lighting",
      "Circuit Breakers & Panels",
      "Fans & Ventilation",
      "Accessories",
      "Other",
    ],
    legacyIndustries: ["hardware", "tech"],
  },
  {
    id: "hardware_building",
    label: "Hardware & Building",
    emoji: "🔧",
    workflow: "standard",
    units: ["Pcs", "Kg", "Litre", "Metre", "Roll", "Sheet", "Bag", "Box", "Set", "Pair", "Bundle", "Tin", "Drum"],
    subCategories: [
      "Cement & Concrete",
      "Steel & Iron",
      "Pipes & Plumbing Fittings",
      "Paint & Varnish",
      "Tiles & Flooring",
      "Timber & Wood",
      "Hand Tools & Power Tools",
      "Bolts, Nuts & Fasteners",
      "Roofing & Insulation",
      "Safety Equipment & PPE",
      "Adhesives & Sealants",
      "Doors & Windows",
      "Sanitary Ware",
      "Other",
    ],
    legacyIndustries: ["hardware"],
  },
  {
    id: "grocery_food",
    label: "Grocery & Food",
    emoji: "🛒",
    workflow: "standard",
    units: ["Kg", "G", "Litre", "ML", "Pcs", "Dozen", "Pack", "Sack", "Bottle", "Tin", "Box", "Bundle", "Tray", "Carton"],
    subCategories: [
      "Rice & Grains",
      "Flour & Pulses",
      "Vegetables & Fruits",
      "Dairy & Eggs",
      "Meat & Poultry",
      "Seafood",
      "Cooking Oil & Ghee",
      "Spices & Condiments",
      "Beverages & Drinks",
      "Snacks & Confectionery",
      "Bakery & Bread",
      "Frozen Foods",
      "Cleaning & Household",
      "Personal Care",
      "Other",
    ],
    legacyIndustries: ["grocery"],
  },
  {
    id: "fashion_apparel",
    label: "Fashion & Apparel",
    emoji: "👗",
    workflow: "standard",
    units: ["Pcs", "Pair", "Dozen", "Set", "Metre", "Roll", "Box", "Bundle"],
    subCategories: [
      "Men's Clothing",
      "Women's Clothing",
      "Children's Clothing",
      "Footwear & Shoes",
      "Bags & Handbags",
      "Belts & Wallets",
      "Jewellery & Accessories",
      "Sportswear",
      "Fabric & Textiles",
      "Other",
    ],
    legacyIndustries: ["fashion"],
  },
  {
    id: "pharmacy_health",
    label: "Health & Pharmacy",
    emoji: "💊",
    workflow: "standard",
    units: ["Pcs", "Strip", "Bottle", "Box", "ML", "G", "Sachet", "Tube", "Vial", "Pack"],
    subCategories: [
      "Prescription Medicines",
      "OTC Medicines",
      "Vitamins & Supplements",
      "Medical Supplies",
      "Baby & Mother Care",
      "Personal Care",
      "Optical",
      "Other",
    ],
    legacyIndustries: ["pharmacy"],
  },
  {
    id: "jewelry_watches",
    label: "Jewelry & Watches",
    emoji: "💍",
    workflow: "standard",
    units: ["Pcs", "Gram", "Sovereign", "Carat", "Tola", "Set", "Pair"],
    subCategories: [
      "Gold Jewelry",
      "Silver Jewelry",
      "Diamond Jewelry",
      "Watches & Clocks",
      "Chains & Necklaces",
      "Rings & Bands",
      "Loose Gems & Stones",
      "Other",
    ],
    legacyIndustries: ["jewelry"],
  },
  {
    id: "automotive",
    label: "Automotive",
    emoji: "🚗",
    workflow: "standard",
    units: ["Pcs", "Litre", "Set", "Pair", "Box", "Roll", "Metre", "Kit", "Drum", "Bottle"],
    subCategories: [
      "Engine Parts",
      "Body Parts",
      "Electrical & Ignition",
      "Tyres & Wheels",
      "Batteries",
      "Lubricants & Oil",
      "Filters",
      "Brakes & Clutch",
      "Car Accessories",
      "Motorcycle Parts",
      "Other",
    ],
    legacyIndustries: ["automotive"],
  },
  {
    id: "agriculture",
    label: "Agriculture & Livestock",
    emoji: "🌾",
    workflow: "standard",
    units: ["Kg", "G", "Litre", "ML", "Bag", "Pcs", "Bundle", "Box", "Sack", "Bottle", "Pack", "Roll"],
    subCategories: [
      "Seeds & Seedlings",
      "Fertilizers",
      "Pesticides",
      "Animal Feed",
      "Veterinary Medicines",
      "Farm Tools",
      "Irrigation",
      "Organic Products",
      "Other",
    ],
    legacyIndustries: ["agriculture"],
  },
  {
    id: "general_retail",
    label: "General Retail",
    emoji: "🏪",
    workflow: "standard",
    units: ["Pcs", "Box", "Set", "Pair", "Dozen", "Metre", "Litre", "Kg", "Roll", "Bundle", "Sheet", "Hour", "Job"],
    subCategories: [
      "General Merchandise",
      "Stationery & Office",
      "Sports & Fitness",
      "Toys & Games",
      "Books & Media",
      "Gifts & Novelties",
      "Home Décor",
      "Beauty & Salon",
      "Services & Labour",
      "Miscellaneous",
      "Other",
    ],
    legacyIndustries: ["general", "tech"],
  },
];

export function getCategoryGroupById(id) {
  return CATEGORY_GROUPS.find(function (g) { return g.id === id; }) || null;
}

export function getCategoryGroupForSubCategory(subCategory) {
  var name = String(subCategory || "").trim();
  if (!name) return null;
  for (var i = 0; i < CATEGORY_GROUPS.length; i++) {
    var g = CATEGORY_GROUPS[i];
    if ((g.subCategories || []).indexOf(name) >= 0) return g;
  }
  return null;
}
